### ISSUE TITLE
Customize the welcome screen that people see

### ISSUE THREAD

**Issue by MarkBennett** [devedmonton/gavel#4]
Just going through the testing and realized that one place we might want to customize is the welcome screen people see when they first sign into Gavel:

![Screen Shot 2020-04-28 at 8 27 23 PM](https://user-images.githubusercontent.com/61872/80555844-ba2b9080-898e-11ea-8744-4c3fbbf12645.png)

The text on this page comes from [`constants.py`](https://github.com/devedmonton/gavel/blob/master/gavel/constants.py#L19).

Some things we might want to add are:

1) link to training slides

**Comment by ajyong** [comment]
Oh wait... this looks like Markdown.  Maybe I can add a URL in here.

I'll work on tweaking the invite email first though, that one has a higher chance of success at the moment.
